### ISSUE TITLE
The future of noddos?

### ISSUE THREAD

**Issue by tapper82** [noddos/noddos#52]
Hi I would like to ask what is going on with this project? What are your  plans? The concept of the package seems sound, but when I install it on my router I fail to see what it's doing. It would help if I could see how it's keeping me safe. It's hard to see if it is even working/running from the Luci interface. In the list of devices somthing pops up that I don't want to have access to my wan I would like to be able to block it. Why should I send your stats. If the stats are really helpful then make a post on the openwrt forums and more people will get involved.

**Comment by StevenHessing** [comment]
Hi,

Thanks for your interest. I've not been able to spend much time on noddos
since November last year. I did spend some time on improving quality by
writing test cases and fixing bugs but didn't have the bandwidth to work on
new features.

The original goal was to identify IOT devices in home networks and analyze
their traffic flows so that noddos could block rogue traffic flows. For
that reason noddos has the opt-in option to upload device data and traffic
stats (all the while preserving the privacy of the user)

Right now, all it really does is identify devices that we have in the
device database. Neat but not of significant value for most users and
because of that, not a lot of users installed noddos and enabled the upload
option. That's a pity because I can only add devices to the device database
if users upload the device data.

So I figure I need to make the app more attractive. So the idea is to shift
a bit more to add features for users: allow devices to blocked off from the
Internet or kicked off the wi-fi. And allow devices to be tagged with
keywords and then set firewall rules on if/when devices with certain
keywords are allowed to connect to the Internet (ie no Internet for kids
after 9pm, or block Internet access during dinner time). With those kind of
features, noddos may get more interesting for users.

If that turns out to be true, I should get more device data and traffic
data uploaded and that would allow me to start looking at blocking traffic
of rogue devices again.But again, the issue right now is to find time to
work in noddos next to my various other commitments.

- Steven

**Comment by tapper82** [comment]
Thanks that is what I was hoping for. I will get involved when you make any changes. I will be happy to do testing. Thanks for laying down your plans.

**Comment by sixeyeco** [comment]
I installed it believing I could monitor traffic flow per device. 

I don't see anywhere in Noddos clients or Noddos clients tracking where the traffic information is displayed. 

Also, I can't find where I should edit the LanInterfaces list. 

Any help would be greatly appreciated.
